name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Publish Docker
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Publish to Docker hub
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: jonay2000/netecho
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            dockerfile: Dockerfile